### ISSUE TITLE
nix build failing due to git lfs issue

### ISSUE THREAD

**Issue by felschr** [cosmic-nix/cosmic-flake#2]
```console
❯ nix build "github:cosmic-nix/cosmic-flake#all"
evaluating derivation 'github:cosmic-nix/cosmic-flake#all'Downloading screenshots/arabic.png (214 KB)
Error downloading object: screenshots/arabic.png (3899436): Smudge error: Error downloading screenshots/arabic.png (38994360da746e9331c0f0ff
cc637d3342be5d0d568c25ffeb7d908b5c40be95): batch request: missing protocol: ""

Errors logged to '/tmp/nix-253075-1/lfs/logs/20231005T223220.718807412.log'.
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: screenshots/arabic.png: smudge filter lfs failed
error: program 'git' failed with exit code 128
(use '--show-trace' to show detailed location information)
```

Apparently this is an issue with nix itself: https://github.com/NixOS/nix/issues/4623

@colemickens But it seems like you've got this working in your local setup somehow?
Would you mind sharing your setup?

**Comment by felschr** [comment]
Ah, just found the workaround mentioned in https://github.com/NixOS/nix/issues/4623#issuecomment-1270580999.
I've somehow overlooked it the first time I skimmed through the issue.

**Comment by colemickens** [comment]
1. I didn't hit that and didn't have to do anything special to get it to build?
2. The bigger issue is that now every cosmic component (or nearly every component) is hitting this issue: https://github.com/pop-os/xdg-desktop-portal-cosmic/issues/8

Which at least means maybe there's a common dep, recently added, that we can track down, but I havent' had time to look at it yet.

**Comment by colemickens** [comment]
I'm also wondering if somehow I avoid this issue you're reporting because I have a more complete git available system-wide? I'm not sure how pure the git fetcher is? It is odd though, I definitely don't have any other env vars set, I've just been running `nix develop -c ./main.nu update` to update/build.
